id: P000639
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2370
  title: ཚེ་འདས་ཟས་བསྔོ།
  author: ''
  volumes:
    4c3bc3f7b677443fafc962c41396b839:
      image_group_id: I3CN2372
      title: ''
      volume_number: 1
      total_pages: 44
