id: IA1301CEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:32:24+00:00'
last_modified: '2022-06-07T12:31:57.699465+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2370
  title: ཚེ་འདས་ཟས་བསྔོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    97AD:
      image_group_id: I3CN2372
      title: ''
      total_pages: 44
      order: 1
      base_file: 97AD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
